/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 scene.gltf
Author: Shadow (https://sketchfab.com/jaydenelizondo7)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/little-astronaut-2898a4b265d943919ca830e7d746ac13
Title: Little-astronaut
*/

import React, { useRef, useState, useEffect } from 'react'
import { useGLTF,  useAnimations, KeyboardControls } from '@react-three/drei'
import {useThree, useSphere} from '@react-three/fiber'
import useKeyboardControls from "./controls"

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/scene.gltf')
  const { ref, actions, names } = useAnimations(animations, group)

  const [index, setIndex] = useState(4)

  useEffect(() => {
    // Reset and fade in animation after an index has been changed
    actions[names[index]].play()
    // In the clean-up phase, fade it out
    return 
  }, )
  
  
  
  const { camera } = useThree()


  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} position={[0, -1, 0]} >
          <group name="astronautfbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Armature" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <group name="Object_6">
                    <primitive object={nodes._rootJoint}  />
                    <group name="Object_8" position={[0, 76.08, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <skinnedMesh ref={ref} name="Object_9" geometry={nodes.Object_9.geometry} material={materials.Astronaut} skeleton={nodes.Object_9.skeleton} onClick={() => setIndex((index + 1) % names.length)}/>
                   
                  </group>
                </group>
                <group name="Astronaut" position={[0, 76.08, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
